apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-site-example-ingress
  namespace: site-example-demo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: site-example.lab-cesi.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: site-example-svc
            port:
              number: 80