apiVersion: v1
kind: Service
metadata:
  name: site-example-svc
  labels:
    app: site-example-svc
  namespace: site-example-demo
spec:
  ports:
    - port: 80
  selector:
    app: site-example
  type: ClusterIP